<a href="https://colab.research.google.com/github/Omara455/Machine-Learning-Journey/blob/main/House_Pricing_DTR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Decision Tree Regression

## Importing the libraries

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [7]:
dataset = pd.read_csv('house_pricing_dt.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Encoding Categorical Data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [27]:
print(X)

[[1.0 0.0 0.0 ... 39 7.8 3]
 [0.0 0.0 1.0 ... 29 10.6 4]
 [0.0 1.0 0.0 ... 15 5.5 9]
 ...
 [1.0 0.0 0.0 ... 24 1.8 4]
 [0.0 0.0 1.0 ... 15 0.8 5]
 [0.0 1.0 0.0 ... 32 0.7 5]]


## Split

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [26]:
print(X_train)

[[0.0 0.0 1.0 ... 35 0.3 4]
 [1.0 0.0 0.0 ... 35 5.6 4]
 [0.0 0.0 0.0 ... 6 11.1 2]
 ...
 [1.0 0.0 0.0 ... 10 0.2 4]
 [0.0 0.0 1.0 ... 14 12.0 10]
 [1.0 0.0 0.0 ... 3 3.5 10]]


## Training the Decision Tree Regression model on the whole dataset

In [12]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

## Predicting a new result

In [23]:
y_pred = regressor.predict(X_test)

df_comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(df_comparison)


      Actual  Predicted
0   376000.0   378300.0
1   224300.0   238200.0
2   335000.0   354800.0
3   295900.0   299000.0
4   208100.0   240800.0
5   347400.0   337100.0
6   245000.0   228000.0
7   188700.0   196900.0
8   349700.0   369200.0
9   322100.0   315300.0
10  280200.0   230000.0
11  258600.0   248500.0
12  275600.0   304300.0
13  313300.0   346000.0
14  371500.0   367200.0
15  217600.0   200500.0
16  288800.0   290400.0
17  343700.0   307600.0
18  354300.0   406900.0
19  304600.0   325300.0
20  313200.0   350500.0
21  266000.0   238200.0
22  232600.0   228000.0
23  369900.0   376100.0
24  331100.0   337300.0
25  279500.0   285200.0
26  431100.0   388900.0
27  404500.0   439100.0
28  356900.0   354100.0
29  268900.0   242300.0
30  317400.0   252900.0
31  238900.0   251100.0
32  432400.0   407900.0
33  283400.0   307300.0
34  299000.0   275600.0
35  310400.0   310300.0
36  363500.0   381200.0
37  286400.0   322600.0
38  255700.0   299600.0
39  292400.0   269500.0


## Visualising the Decision Tree Regression results (For 1D)

In [24]:
# X_grid = np.arange(min(X), max(X), 0.01)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
# plt.title('Truth or Bluff (Decision Tree Regression)')
# plt.xlabel('Position level')
# plt.ylabel('Salary')
# plt.show()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()