<a href="https://colab.research.google.com/github/Omara455/Machine-Learning-Journey/blob/main/Laptop_Pricing_RFR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Regression

## Importing the libraries

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [23]:
dataset = pd.read_csv('laptop_pricing_rf.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Encoding Categorical Data

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2,3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1.0 16 512]
 [1.0 0.0 0.0 ... 0.0 64 512]
 [0.0 0.0 1.0 ... 0.0 16 1024]
 ...
 [1.0 0.0 0.0 ... 1.0 64 256]
 [0.0 1.0 0.0 ... 0.0 64 2048]
 [1.0 0.0 0.0 ... 0.0 32 2048]]


## Split

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [26]:
print(X_train)

[[0.0 0.0 1.0 ... 0.0 32 2048]
 [0.0 0.0 1.0 ... 0.0 8 256]
 [1.0 0.0 0.0 ... 0.0 32 512]
 ...
 [0.0 0.0 1.0 ... 0.0 64 2048]
 [0.0 1.0 0.0 ... 0.0 16 2048]
 [0.0 0.0 1.0 ... 0.0 8 1024]]


## Training the Random Forest Regression model on the whole dataset

In [27]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

## Predicting a new result

In [28]:
y_pred = regressor.predict(X_test)

df_comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(df_comparison)

    Actual    Predicted
0   1350.0  1108.423810
1   1470.0  1571.500000
2   1410.0  1254.304762
3   1820.0  1828.625000
4    690.0   789.115079
5   1110.0  1089.177381
6    630.0   660.666667
7    840.0   747.172413
8   1100.0  1079.866667
9    940.0   903.000000
10  1100.0  1143.084524
11  1300.0  1285.677381
12  1990.0  1629.907143
13  1320.0  1254.304762
14  1060.0  1126.075000
15   760.0   784.351190
16   940.0   946.833333
17  1730.0  1772.666667
18   910.0  1004.546999
19  1200.0  1143.084524
20  1530.0  1620.875000
21  2230.0  1919.000000
22  1090.0  1004.546999
23  1350.0  1501.833333
24  1180.0  1108.423810
25   580.0   614.666667
26   950.0  1004.546999
27   730.0   747.172413
28   810.0   784.351190
29  1190.0  1079.866667
30  1620.0  1656.666667
31   860.0   903.000000
32  1360.0  1501.833333
33   730.0   967.200000
34   700.0   784.351190
35   910.0  1004.546999
36  1040.0  1004.546999
37  1010.0  1079.866667
38  1300.0  1328.200000
39   400.0   443.327778
40   860.0   926

## Visualising the Random Forest Regression results (optional)

In [29]:
# X_grid = np.arange(min(X), max(X), 0.01)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
# plt.title('Truth or Bluff (Random Forest Regression)')
# plt.xlabel('Position level')
# plt.ylabel('Salary')
# plt.show()