<a href="https://colab.research.google.com/github/Omara455/Machine-Learning-Journey/blob/main/Student_Final_Score_Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Import Data

In [9]:
dataset = pd.read_csv('student_final_score.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Encoding Categorical Variables

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 6.0 0.9 89]
 [1.0 0.0 0.0 4.7 2.4 91]
 [0.0 0.0 1.0 6.3 2.5 96]
 [0.0 0.0 1.0 8.0 1.8 96]
 [0.0 0.0 1.0 4.5 2.8 71]
 [0.0 1.0 0.0 4.5 3.6 76]
 [1.0 0.0 0.0 8.2 5.8 90]
 [0.0 0.0 1.0 6.5 3.3 90]
 [1.0 0.0 0.0 4.1 3.4 90]
 [0.0 0.0 1.0 6.1 2.9 124]
 [0.0 0.0 1.0 4.1 0.1 91]
 [0.0 1.0 0.0 4.1 3.0 96]
 [0.0 0.0 1.0 5.5 3.1 95]
 [0.0 0.0 1.0 1.2 6.7 92]
 [1.0 0.0 0.0 1.6 2.7 82]
 [0.0 0.0 1.0 3.9 3.5 93]
 [0.0 1.0 0.0 3.0 2.9 77]
 [0.0 0.0 1.0 5.6 1.2 83]
 [1.0 0.0 0.0 3.2 4.7 80]
 [0.0 0.0 1.0 2.2 4.1 86]
 [1.0 0.0 0.0 7.9 4.2 108]
 [1.0 0.0 0.0 4.5 1.6 66]
 [0.0 0.0 1.0 5.1 5.1 92]
 [1.0 0.0 0.0 2.2 0.9 69]
 [1.0 0.0 0.0 3.9 3.9 80]
 [0.0 0.0 1.0 5.2 6.3 96]
 [0.0 0.0 1.0 2.7 1.5 86]
 [0.0 1.0 0.0 5.8 2.2 74]
 [0.0 1.0 0.0 3.8 3.1 78]
 [0.0 1.0 0.0 4.4 2.2 92]
 [1.0 0.0 0.0 3.8 0.7 78]
 [1.0 0.0 0.0 8.7 3.1 87]
 [0.0 1.0 0.0 5.0 1.4 85]
 [0.0 0.0 1.0 2.9 3.7 78]
 [0.0 0.0 1.0 6.6 1.6 106]
 [0.0 0.0 1.0 2.6 5.3 91]
 [1.0 0.0 0.0 5.4 1.8 65]
 [0.0 1.0 0.0 1.1 2.5 87]
 [1.0 0.0

Splitting Training and Test Datasets

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Training Multiple Linear Regression Model

In [13]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

Predic Test Results

In [14]:
y_pred = regressor.predict(X_test)
df_comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(df_comparison)

    Actual  Predicted
0     21.6  23.996735
1     36.0  37.331066
2     32.6  37.157519
3     38.5  35.590386
4     42.8  38.654514
5     14.1  25.402150
6     31.9  24.450070
7     44.1  40.568928
8     33.6  36.000766
9     32.6  23.808716
10    24.9  36.075414
11    29.5  29.945504
12    32.8  33.344227
13    38.6  33.022751
14    39.9  38.947641
15    19.9  21.559873
16    33.4  39.694860
17    29.5  29.680782
18    24.6  28.907721
19    31.0  30.119435
